-- initdb.sql

-- Criar tabela USUARIO
CREATE TABLE usuario (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    senha VARCHAR2(100) NOT NULL
);

-- Inserir dados na tabela USUARIO
INSERT INTO usuario (nome, email, senha) VALUES ('João Silva', 'joao.silva@example.com', 'senha123');
INSERT INTO usuario (nome, email, senha) VALUES ('Maria Oliveira', 'maria.oliveira@example.com', 'senha456');
INSERT INTO usuario (nome, email, senha) VALUES ('Carlos Souza', 'carlos.souza@example.com', 'senha789');
INSERT INTO usuario (nome, email, senha) VALUES ('Ana Pereira', 'ana.pereira@example.com', 'senha321');
INSERT INTO usuario (nome, email, senha) VALUES ('Luís Fernandes', 'luis.fernandes@example.com', 'senha654');

-- Criar tabela FONTE_DE_RECEITA com FK para USUARIO
CREATE TABLE fonte_de_receita (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    descricao VARCHAR2(200) NOT NULL,
    valor NUMBER(10,2) NOT NULL,
    usuario_id NUMBER NOT NULL,
    CONSTRAINT fk_usuario_receita FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE
);

-- Criar índice na coluna usuario_id de FONTE_DE_RECEITA
CREATE INDEX idx_fonte_receita_usuario ON fonte_de_receita(usuario_id);

-- Inserir dados na tabela FONTE_DE_RECEITA
INSERT INTO fonte_de_receita (descricao, valor, usuario_id) VALUES ('Salário Mensal', 5000.00, 1);
INSERT INTO fonte_de_receita (descricao, valor, usuario_id) VALUES ('Freelance Projeto X', 1500.00, 2);
INSERT INTO fonte_de_receita (descricao, valor, usuario_id) VALUES ('Aluguel de Imóvel', 2000.00, 3);
INSERT INTO fonte_de_receita (descricao, valor, usuario_id) VALUES ('Venda de Artesanato', 750.00, 4);
INSERT INTO fonte_de_receita (descricao, valor, usuario_id) VALUES ('Dividendos de Ações', 300.00, 5);

-- Criar tabela GASTO com FK para USUARIO
CREATE TABLE gasto (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    descricao VARCHAR2(200) NOT NULL,
    valor NUMBER(10,2) NOT NULL,
    usuario_id NUMBER NOT NULL,
    CONSTRAINT fk_usuario_gasto FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE
);

-- Criar índice na coluna usuario_id de GASTO
CREATE INDEX idx_gasto_usuario ON gasto(usuario_id);

-- Inserir dados na tabela GASTO
INSERT INTO gasto (descricao, valor, usuario_id) VALUES ('Aluguel', 1500.00, 1);
INSERT INTO gasto (descricao, valor, usuario_id) VALUES ('Supermercado', 800.00, 2);
INSERT INTO gasto (descricao, valor, usuario_id) VALUES ('Energia Elétrica', 200.00, 3);
INSERT INTO gasto (descricao, valor, usuario_id) VALUES ('Internet', 100.00, 4);
INSERT INTO gasto (descricao, valor, usuario_id) VALUES ('Transporte', 300.00, 5);

-- Criar tabela DIVIDA com FK para USUARIO
CREATE TABLE divida (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    descricao VARCHAR2(200) NOT NULL,
    valor NUMBER(10,2) NOT NULL,
    taxa_juros NUMBER(5,2) NOT NULL,
    meses_para_pagar NUMBER NOT NULL,
    usuario_id NUMBER NOT NULL,
    CONSTRAINT fk_usuario_divida FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE
);

-- Criar índice na coluna usuario_id de DIVIDA
CREATE INDEX idx_divida_usuario ON divida(usuario_id);

-- Inserir dados na tabela DIVIDA
INSERT INTO divida (descricao, valor, taxa_juros, meses_para_pagar, usuario_id) VALUES ('Empréstimo Carro', 20000.00, 1.5, 48, 1);
INSERT INTO divida (descricao, valor, taxa_juros, meses_para_pagar, usuario_id) VALUES ('Financiamento Imobiliário', 300000.00, 0.9, 360, 2);
INSERT INTO divida (descricao, valor, taxa_juros, meses_para_pagar, usuario_id) VALUES ('Empréstimo Pessoal', 5000.00, 2.0, 24, 3);
INSERT INTO divida (descricao, valor, taxa_juros, meses_para_pagar, usuario_id) VALUES ('Cartão de Crédito', 2500.00, 12.0, 6, 4);
INSERT INTO divida (descricao, valor, taxa_juros, meses_para_pagar, usuario_id) VALUES ('Dívida Estudantil', 30000.00, 1.0, 60, 5);

-- Criar tabela INVESTIMENTO com FK para USUARIO
CREATE TABLE investimento (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    descricao VARCHAR2(200) NOT NULL,
    valor NUMBER(10,2) NOT NULL,
    rendimento_mensal NUMBER(5,2) NOT NULL,
    usuario_id NUMBER NOT NULL,
    CONSTRAINT fk_usuario_investimento FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE
);

-- Criar índice na coluna usuario_id de INVESTIMENTO
CREATE INDEX idx_investimento_usuario ON investimento(usuario_id);

-- Inserir dados na tabela INVESTIMENTO
INSERT INTO investimento (descricao, valor, rendimento_mensal, usuario_id) VALUES ('Tesouro Direto', 10000.00, 0.5, 1);
INSERT INTO investimento (descricao, valor, rendimento_mensal, usuario_id) VALUES ('CDB Banco X', 20000.00, 0.6, 2);
INSERT INTO investimento (descricao, valor, rendimento_mensal, usuario_id) VALUES ('Ações Empresa Y', 15000.00, 1.2, 3);
INSERT INTO investimento (descricao, valor, rendimento_mensal, usuario_id) VALUES ('Fundos Imobiliários', 25000.00, 0.8, 4);
INSERT INTO investimento (descricao, valor, rendimento_mensal, usuario_id) VALUES ('Poupança', 5000.00, 0.3, 5);

-- Criar tabela META_FINANCEIRA com FK para USUARIO
CREATE TABLE meta_financeira (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    descricao VARCHAR2(200) NOT NULL,
    valor_objetivo NUMBER(10,2) NOT NULL,
    valor_atual NUMBER(10,2) DEFAULT 0,
    usuario_id NUMBER NOT NULL,
    CONSTRAINT fk_usuario_meta FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE
);

-- Criar índice na coluna usuario_id de META_FINANCEIRA
CREATE INDEX idx_meta_usuario ON meta_financeira(usuario_id);

-- Inserir dados na tabela META_FINANCEIRA
INSERT INTO meta_financeira (descricao, valor_objetivo, valor_atual, usuario_id) VALUES ('Viagem Internacional', 15000.00, 3000.00, 1);
INSERT INTO meta_financeira (descricao, valor_objetivo, valor_atual, usuario_id) VALUES ('Compra de Carro', 50000.00, 10000.00, 2);
INSERT INTO meta_financeira (descricao, valor_objetivo, valor_atual, usuario_id) VALUES ('Reserva de Emergência', 20000.00, 8000.00, 3);
INSERT INTO meta_financeira (descricao, valor_objetivo, valor_atual, usuario_id) VALUES ('Curso de Especialização', 10000.00, 2000.00, 4);
INSERT INTO meta_financeira (descricao, valor_objetivo, valor_atual, usuario_id) VALUES ('Reforma da Casa', 30000.00, 5000.00, 5);

COMMIT;
